name: Environment variables

on:
 push:
  branches:
   - main
   - dev

jobs:
 echo-context:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Github Context
     run: |
      echo "Actor is ${{github.actor}}"
      echo "Ref is ${{github.ref}}"
      echo "event name is ${{github.event_name}}"
   - name: Set branch name
     run: |
      GIT_BRANCH=${{github.ref}}
      echo "branch is set to $GIT_BRANCH"
