name: Context variables
on:
 push:
  branches:
   - main
   - dev

jobs:
 echo-context-variables:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Context Variables
     run: |
      echo "Event name is ${{github.event_name}}"
      echo "Actor is ${{github.actor}}"
      echo "USER=${{github.actor}}"
