name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js (Example)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && success() && github.event.check_suite.status == 'completed'
    steps:
      - name: Deploy Application
        run: echo "Deploying to production environment..."
