name: Deploy to Staging

on:
  push:
    branches:
      - Develop  # Ensure this matches the exact branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (example)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: stag  # Ensure 'stag' is correctly set up in your GitHub settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging environment..."
          # Add your deployment commands here
