name: envcontext

on:
 push:

env:
 VAR: 'test1'

jobs:
 echo-envcontext:

  env:
   VAR: 'test2'
  runs-on: ubuntu-latest
  steps:
   - run: echo "environment context ${{env.VAR}}"
     env:
      VAR: 'test3'
