name: input
run-name: Input DEBUG - ${{inputs.debug}}
on:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    required: false

jobs:
 echo-input:
  runs-on: ubuntu-latest
  steps:
   - run:  echo "check the input"
 
 
