name: Java Project


on:
 push:
 workflow_dispatch:

jobs:
 echo-java-job:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Setup Java JDK
     uses: actions/setup-java@v4.7.0
     with:
      java-version: '17'
      distribution: 'temurin'
