name: secrets context

on:
  workflow_dispatch

jobs:
 echo-secret:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Username is ${{secrets.USERNAME}}
   - run: echo "Passowrd is ${{secrets.PASSWORD}}
  
 
